# Generated by Django 5.2.7 on 2025-11-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0010_alter_syllabus_class_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='course',
            name='prof_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='class_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser.course'),
        ),
    ]
