# Generated by Django 5.2.7 on 2025-11-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_alter_course_course_code_alter_course_prof_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
