# Generated by Django 5.2.8 on 2025-11-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_alter_course_course_code_alter_course_prof_email_and_more'),
        ('parser', '0011_user_notification_token_alter_course_course_code_and_more'),
    ]

    operations = [
    ]
