# Generated by Django 5.2.7 on 2025-11-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_alter_deadline_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prof_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
