# Generated by Django 5.2.8 on 2025-11-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_merge_20251120_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
