# Generated by Django 5.2.7 on 2025-11-23 17:24

import core.services.randomColour
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0013_alter_course_prof_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default=core.services.randomColour.generate_colour, max_length=7),
        ),
    ]
