# Generated by Django 5.2.7 on 2025-11-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0014_course_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='color',
            new_name='colour',
        ),
    ]
