# Generated by Django 5.2.7 on 2025-11-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0015_rename_color_course_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=15),
        ),
    ]
