# Generated by Django 5.2.7 on 2025-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0016_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyperiod',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
