# Generated by Django 5.2.7 on 2025-11-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0013_alter_deadline_due_date'),
        ('parser', '0017_alter_policyperiod_time'),
    ]

    operations = [
    ]
