# Generated by Django 5.2.7 on 2025-11-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0018_merge_20251125_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='prof_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='policyperiod',
            name='time',
            field=models.FloatField(default=0.0),
        ),
    ]
